# Generated by Django 5.0.1 on 2024-01-20 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chat",
            name="role",
            field=models.CharField(max_length=255),
        ),
    ]
